# spring.application.name=backend

# spring.datasource.url=jdbc:mysql://localhost:3306/Authorization
# spring.datasource.username=root
# spring.datasource.password=klu123

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# spring.application.name=backend

# spring.datasource.url=jdbc:postgresql://localhost:5432/Authorization
# spring.datasource.username=postgres
# spring.datasource.password=klu123

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# render

spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}